bonitasoft/bonita-openapi

.github/workflows/build.yml, package.json
Signed-off-by: Romain Bioteau <romain.bioteau@bonitasoft.com>
=> build(actions): add github action to build pr and master

openapi/paths/API@living@application.yaml
covers [BR-615](https://bonitasoft.atlassian.net/browse/BR-615)
=> feat(application API): Add new filter by userId to application API

.github/workflows/build.yml, 42c-conf.yaml, openapi/components/schemas/Bdm.yaml, openapi/openapi.yaml
Signed-off-by: Romain Bioteau <romain.bioteau@bonitasoft.com>
=> feat(audit): add 42c static analysis

openapi/openapi.yaml, openapi/paths/API@bpm@processConnector@{id}@{connectorImplId}@{connectorImplVersion}.yaml, openapi/paths/portal@applicationsUpload.yaml, openapi/paths/portal@bdmAccessControlUpload.yaml, openapi/paths/portal@fileUpload.yaml, openapi/paths/portal@organizationUpload.yaml, openapi/paths/portal@pageUpload.yaml, openapi/paths/portal@processUpload.yaml, openapi/paths/portal@profilesUpload.yaml
- Add `/API/bpm/processConnector/{id}/{connectorImplId}/{connectorImplVersion}` documentation
-  Regroup all upload API under the portal menu ( specific menu entries like process, process etc. still have an entry for upload doc)
=> feat(upload): add process connector update, re-order files upload doc

openapi/components/schemas/ProcessInfo.yaml, openapi/openapi.yaml, openapi/paths/API@bpm@caseInfo@{id}.yaml, openapi/paths/API@bpm@processInfo@{id}.yaml
* add new resource
* specify all possible states
* indicate caseInfo is an enterprise resource
Covers [RUNTIME-1202](https://bonitasoft.atlassian.net/browse/RUNTIME-1202)
=> feat(processInfo API resource): add processInfo resource

openapi/paths/API@bpm@humanTask.yaml
Add missing filters to the description:
- user_id
- show_assigned_to_others
closes [RUNTIME-1309](https://bonitasoft.atlassian.net/browse/RUNTIME-1309)
=> chore(humanTask): update GET request description

openapi/paths/loginservice.yaml
=> feat(login): Correct the success status code

README.adoc, openapi/components/schemas/SystemTenant.yaml, openapi/components/schemas/Tenant.yaml, openapi/components/schemas/TenantCreateRequest.yaml, openapi/components/schemas/TenantUpdateRequest.yaml, openapi/components/schemas/ThemeCreateRequest.yaml, openapi/components/schemas/ThemeRestoreRequest.yaml, openapi/openapi.yaml, openapi/paths/API@platform@tenant.yaml, openapi/paths/API@platform@tenant@{id}.yaml, openapi/paths/API@portal@profileEntry.yaml, openapi/paths/API@portal@profileEntry@{id}.yaml, openapi/paths/API@portal@theme.yaml, openapi/paths/API@portal@theme@unusedId.yaml
* theme
* profileEntry
* tenant (except update tenant)
=> tr(apis): deprecate some old apis

openapi/components/schemas/ConnectorInstance.yaml, openapi/components/schemas/ProcessInstance.yaml
refers to [BTT-30](https://bonitasoft.atlassian.net/browse/BTT-30)
Narrow values for some properties that should be enums.
=> fix(BTT-30): fix missing enums

.github/workflows/build.yml, .github/workflows/release.yml
* on Pr, deploy a site on surge
* when PR is closed, this site will be destroyed automatically
=> feat(preview): Deploy Pr preview

.github/workflows/release.yml
* Push release commit to keep package.json and openapi.yaml file up-to-date
* Stop do release when push on release branch and start it only from workflow
=> refactor(release): Release refactoring

docs/index.html.hbs
* add description, keyword and author
=> feat(tag): Adding tag

.github/release.yml, README.adoc
* Automatically generate release note from pull request label
=> chore(release): Generated release note

README.adoc
* Add a paragraph to list action to be done after a release
=> docs: Update release info

openapi/paths/API@bpm@archivedCaseDocument.yaml
Fix inconsistency between spec and code.
Closes RUNTIME-1615
=> fix(archivedDocument): replace `archivedProcessInstanceId` filter name with `archivedCaseId`

openapi/components/schemas/MaintenanceDetails.yaml, openapi/openapi.yaml, openapi/paths/API@system@maintenance.yaml, openapi/paths/API@system@tenant@{id}.yaml
closes [DEV-523](https://bonitasoft.atlassian.net/browse/DEV-523)
[DEV-523]: https://bonitasoft.atlassian.net/browse/DEV-523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(maintenance): add maintenance API

openapi/components/schemas/ApplicationUpdateRequest.yaml, openapi/paths/API@bpm@actor@{id}.yaml, openapi/paths/API@bpm@process.yaml, openapi/paths/API@bpm@process@{id}.yaml, openapi/paths/API@bpm@processConnector@{id}@{connectorImplId}@{connectorImplVersion}.yaml, openapi/paths/API@bpm@processParameter@{id}@{name}.yaml, openapi/paths/API@form@mapping@{id}.yaml, openapi/paths/API@living@application-menu.yaml, openapi/paths/API@living@application-menu@{id}.yaml, openapi/paths/API@living@application-page.yaml, openapi/paths/API@living@application.yaml, openapi/paths/API@living@application@{id}.yaml, openapi/paths/API@portal@page.yaml, openapi/paths/API@portal@page@{id}.yaml, openapi/paths/API@portal@profile.yaml, openapi/paths/API@portal@profile@{id}.yaml, openapi/paths/API@system@tenant@{id}.yaml, openapi/paths/API@tenant@bdm.yaml, openapi/paths/APIv2@service@install.yaml, openapi/paths/portal@applicationsUpload.yaml, openapi/paths/portal@bdmAccessControlUpload.yaml, openapi/paths/portal@pageUpload.yaml, openapi/paths/portal@processUpload.yaml, openapi/paths/portal@profilesUpload.yaml, openapi/paths/services@application@import.yaml, openapi/paths/services@bdmAccessControl@install.yaml, openapi/paths/services@profile@import.yaml
Those routes are depreciated with the new SCA approach where components are created or updated during the engine startup.
Related to [DEV-541](https://bonitasoft.atlassian.net/browse/DEV-541)
[DEV-541]: https://bonitasoft.atlassian.net/browse/DEV-541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> tr(api): deprecate api routes coming with version 9.0.0

openapi/intro.md
Covers [BPM-58](https://bonitasoft.atlassian.net/browse/BPM-58)
[BPM-58]: https://bonitasoft.atlassian.net/browse/BPM-58?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (like-based search): update the s parameter documentation

.github/workflows/release.yml
To fix the error:
> Error: Resource not accessible by integration
=> fix(release): use BONITA_CI_PAT in github workflow

openapi/components/schemas/AbstractApplication.yaml, openapi/components/schemas/Application.yaml, openapi/components/schemas/ApplicationLink.yaml, openapi/components/schemas/LegacyApplication.yaml, openapi/paths/API@living@application.yaml
Relates to [BPM-139](https://bonitasoft.atlassian.net/browse/BPM-139)
[BPM-139]: https://bonitasoft.atlassian.net/browse/BPM-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(application): Rename AdvancedApplication to ApplicationLink

openapi/components/schemas/SystemInformation.yaml, openapi/openapi.yaml, openapi/paths/API@platform@license.yaml, openapi/paths/API@system@information.yaml, openapi/paths/API@system@license@unusedid.yaml
Relates to https://bonitasoft.atlassian.net/browse/BPM-242
Date are now returned (in the new API) as timestamps, which is better that way 👍🏽 .
Relates to https://github.com/bonitasoft/bonita-engine-sp/pull/3154
=> feat(case counters): document system/information API

openapi/components/schemas/ArchivedBPMFailure.yaml, openapi/components/schemas/BPMFailure.yaml, openapi/openapi.yaml, openapi/paths/API@bpm@archivedFailure@flowNode@{flowNodeInstanceId}.yaml, openapi/paths/API@bpm@failure@flowNode@{flowNodeInstanceId}.yaml
Covers [BPM-316](https://bonitasoft.atlassian.net/browse/BPM-316)
Covers [BPM-328](https://bonitasoft.atlassian.net/browse/BPM-328)
[BPM-316]: https://bonitasoft.atlassian.net/browse/BPM-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[BPM-328]: https://bonitasoft.atlassian.net/browse/BPM-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(BPM failure): add BPM failures API resources

openapi/components/schemas/ArchivedBPMFailure.yaml, openapi/components/schemas/ArchivedProcessInstance.yaml, openapi/components/schemas/BPMFailure.yaml, openapi/components/schemas/ProcessInstance.yaml, openapi/openapi.yaml, openapi/paths/API@bpm@archivedCase.yaml, openapi/paths/API@bpm@archivedFailure@case@{caseId}.yaml, openapi/paths/API@bpm@archivedFailure@case@{rootCaseId}@childCases.yaml, openapi/paths/API@bpm@case.yaml, openapi/paths/API@bpm@failure@case@{caseId}.yaml, openapi/paths/API@bpm@failure@case@{rootCaseId}@childCases.yaml, openapi/paths/API@bpm@failure@flowNode@{flowNodeInstanceId}.yaml
* add APIs to retrieve BPM failures from a caseId or a rootCaseId
* add new attributes and filters to case resource
Covers [BPM-369](https://bonitasoft.atlassian.net/browse/BPM-369)
[BPM-369]: https://bonitasoft.atlassian.net/browse/BPM-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(BPM failure): add BPM failures APIs for case

openapi/paths/API@bpm@connectorInstance.yaml
Relates to [RUNTIME-1940](https://bonitasoft.atlassian.net/browse/RUNTIME-1940)
[RUNTIME-1940]: https://bonitasoft.atlassian.net/browse/RUNTIME-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ConnectorInstance): add missing filters

openapi/openapi.yaml, openapi/paths/loginservice.yaml, openapi/paths/logoutservice.yaml
* remove rest of the PortalAuthentication endpoint (that had already been removed partially)
* restore Content for 204 login response (otherwise a method returning void is generated client-side and it is impossible to read the headers from the response)
=> refactor(Authentication): remove portal auth and fix login response

.github/workflows/build.yml, .github/workflows/release.yml
Relates to https://bonitasoft.atlassian.net/browse/BPM-479
=> chore(GH): update runners to ubuntu-24.04

openapi/paths/API@bpm@humanTask.yaml
Covers [RUNTIME-1957](https://bonitasoft.atlassian.net/browse/RUNTIME-1957)
[RUNTIME-1957]: https://bonitasoft.atlassian.net/browse/RUNTIME-1957?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(humanTask): wrong filter names

openapi/components/schemas/BusinessDataImportResult.yaml, openapi/components/schemas/BusinessDataUpdateResult.yaml, openapi/paths/API@bdm@businessData@{businessDataType}@import.yaml, openapi/paths/API@bdm@businessData@{businessDataType}@{persistenceId}.yaml
=> fix(business data api): fix wrong BDM operation responses
